use bigdecimal::BigDecimal;
use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

#[derive(Debug, Clone, FromRow, Serialize, Deserialize)]
pub struct Lease {
    pub id: Uuid,
    pub property_id: Uuid,
    pub tenant_id: Uuid,
    /// Ordered set of all named tenants (parties) of the lease, primary first.
    /// For a colocation lease this lists every colocataire.
    pub tenant_ids: Vec<Uuid>,
    pub start_date: NaiveDate,
    pub end_date: Option<NaiveDate>,
    pub duration_months: i32,
    pub monthly_rent: BigDecimal,
    pub charges: BigDecimal,
    pub deposit: BigDecimal,
    pub rent_revision: bool,
    pub annual_charges_regularization: bool,
    pub lease_kind: String,
    pub is_colocation: bool,
    pub tenant_count: i32,
    pub destination: String,
    pub habitable_surface: Option<BigDecimal>,
    pub main_room_count: Option<i32>,
    pub heating_mode: Option<String>,
    pub hot_water_mode: Option<String>,
    pub dpe_class: Option<String>,
    pub is_dom_tom: bool,
    pub energy_cost_annual: Option<String>,
    pub energy_cost_year: Option<i32>,
    pub rent_payment_frequency: String,
    pub rent_payment_timing: String,
    pub rent_payment_period: Option<String>,
    pub rent_controlled: bool,
    pub reference_rent: Option<BigDecimal>,
    pub reference_rent_majorated: Option<BigDecimal>,
    pub rent_complement: Option<BigDecimal>,
    pub rent_complement_justification: Option<String>,
    pub previous_tenant_departure_date: Option<NaiveDate>,
    pub previous_tenant_last_rent: Option<BigDecimal>,
    pub professional_mandate: bool,
    pub agency_fee_tenant: Option<BigDecimal>,
    pub agency_fee_landlord: Option<BigDecimal>,
    pub custom_clauses: Option<String>,
    pub inventory_date: Option<NaiveDate>,
    pub private_room_label: Option<String>,
    pub shared_areas_text: Option<String>,
    pub furniture_set_ids: Vec<Uuid>,
    pub furniture_inventory: Option<String>,
    pub dpe: Option<String>,
    pub erp: Option<String>,
    pub home_insurance: Option<String>,
    pub legal_notice_provided: bool,
    pub annex_entry_inventory_provided: bool,
    pub annex_furniture_inventory_provided: bool,
    pub annex_dpe_provided: bool,
    pub annex_erp_provided: bool,
    pub annex_home_insurance_provided: bool,
    pub compliance_status: String,
    pub compliance_errors: Vec<String>,
    pub status: String,
    pub pdf_path: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Deserialize)]
pub struct CreateLease {
    pub property_id: Uuid,
    /// Named tenants (parties) of the lease, in order; the first is the primary.
    /// Colocation requires at least two; otherwise exactly one.
    pub tenant_ids: Vec<Uuid>,
    pub start_date: NaiveDate,
    pub duration_months: i32,
    pub monthly_rent: BigDecimal,
    pub charges: BigDecimal,
    pub deposit: BigDecimal,
    pub rent_revision: bool,
    pub annual_charges_regularization: bool,
    pub lease_kind: Option<String>,
    pub is_colocation: Option<bool>,
    pub destination: Option<String>,
    pub habitable_surface: Option<BigDecimal>,
    pub main_room_count: Option<i32>,
    pub heating_mode: Option<String>,
    pub hot_water_mode: Option<String>,
    pub dpe_class: Option<String>,
    pub is_dom_tom: Option<bool>,
    pub energy_cost_annual: Option<String>,
    pub energy_cost_year: Option<i32>,
    pub rent_payment_frequency: Option<String>,
    pub rent_payment_timing: Option<String>,
    pub rent_payment_period: Option<String>,
    pub rent_controlled: Option<bool>,
    pub reference_rent: Option<BigDecimal>,
    pub reference_rent_majorated: Option<BigDecimal>,
    pub rent_complement: Option<BigDecimal>,
    pub rent_complement_justification: Option<String>,
    pub previous_tenant_departure_date: Option<NaiveDate>,
    pub previous_tenant_last_rent: Option<BigDecimal>,
    pub professional_mandate: Option<bool>,
    pub agency_fee_tenant: Option<BigDecimal>,
    pub agency_fee_landlord: Option<BigDecimal>,
    pub custom_clauses: Option<String>,
    pub inventory_date: Option<NaiveDate>,
    pub private_room_label: Option<String>,
    pub shared_areas_text: Option<String>,
    pub furniture_set_ids: Vec<Uuid>,
    pub furniture_inventory: Option<String>,
    pub dpe: Option<String>,
    pub erp: Option<String>,
    pub home_insurance: Option<String>,
    pub legal_notice_provided: bool,
    pub annex_entry_inventory_provided: Option<bool>,
    pub annex_furniture_inventory_provided: Option<bool>,
    pub annex_dpe_provided: Option<bool>,
    pub annex_erp_provided: Option<bool>,
    pub annex_home_insurance_provided: Option<bool>,
}
