ALTER TABLE leases
ADD COLUMN lease_kind VARCHAR(20) NOT NULL DEFAULT 'standard' CHECK (lease_kind IN ('standard', 'student')),
ADD COLUMN is_colocation BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN tenant_count INTEGER NOT NULL DEFAULT 1 CHECK (tenant_count >= 1),
ADD COLUMN destination VARCHAR(50) NOT NULL DEFAULT 'habitation' CHECK (destination IN ('habitation', 'mixte_professionnel_habitation')),
ADD COLUMN habitable_surface DECIMAL(10, 2),
ADD COLUMN main_room_count INTEGER,
ADD COLUMN heating_mode VARCHAR(20) CHECK (heating_mode IN ('individuel', 'collectif')),
ADD COLUMN hot_water_mode VARCHAR(20) CHECK (hot_water_mode IN ('individuelle', 'collective')),
ADD COLUMN dpe_class VARCHAR(1) CHECK (dpe_class IN ('A', 'B', 'C', 'D', 'E', 'F', 'G')),
ADD COLUMN is_dom_tom BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN energy_cost_annual TEXT,
ADD COLUMN energy_cost_year INTEGER,
ADD COLUMN rent_payment_frequency VARCHAR(20) NOT NULL DEFAULT 'mensuel' CHECK (rent_payment_frequency IN ('mensuel', 'trimestriel')),
ADD COLUMN rent_payment_timing VARCHAR(20) NOT NULL DEFAULT 'a_echoir' CHECK (rent_payment_timing IN ('a_echoir', 'a_terme_echu')),
ADD COLUMN rent_payment_period TEXT,
ADD COLUMN rent_controlled BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN reference_rent DECIMAL(10, 2),
ADD COLUMN reference_rent_majorated DECIMAL(10, 2),
ADD COLUMN rent_complement DECIMAL(10, 2),
ADD COLUMN rent_complement_justification TEXT,
ADD COLUMN previous_tenant_departure_date DATE,
ADD COLUMN previous_tenant_last_rent DECIMAL(10, 2),
ADD COLUMN professional_mandate BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN agency_fee_tenant DECIMAL(10, 2),
ADD COLUMN agency_fee_landlord DECIMAL(10, 2),
ADD COLUMN custom_clauses TEXT,
ADD COLUMN annex_entry_inventory_provided BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN annex_furniture_inventory_provided BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN annex_dpe_provided BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN annex_erp_provided BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN annex_home_insurance_provided BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN compliance_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (compliance_status IN ('pending', 'compliant', 'non_compliant')),
ADD COLUMN compliance_errors TEXT[] NOT NULL DEFAULT '{}';
